// <auto-generated />
namespace ReviewR.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class UsersAndRoles : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201202250000464_UsersAndRoles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO0ZyY7bNvReoP8g6FgglmeKBMnATjCdpQjaWWBN0mNAS88eohSlipQz/rYc+kn9hT5qF0nJsjtxg6I3m+Tb96e/vvw5e/cUMWcDqaAxn7snk6nrAA/ikPL13M3k6sVr993b77+bXYXRk/Oxeneq3iEkF3P3UcrkzPNE8AgREZOIBmks4pWcBHHkkTD2TqfT197J1ANE4SIux5ktMi5pBPkf/HsR8wASmRF2E4fARHmON36O1bklEYiEBDB3F7Ch8Hkx+Q2Wk+K165wzSpATH9hqT7ambxRbbk0QSV4ha3L7sE0gJ4sUYwbtF/jmF9h2DvDoPo0TSOV2AasS7n3oOl4XztMBa7AWjCKNv7j88dR1bjPGyJLhwYowAa6TvDrzZZzCz8AhJRLCeyIlpFzBQs56qYKz5NU4LbzxpqdKCx7hPJZEooUNxjU2lUrUr4pZX6boMK5zTZ8g/BX4Wj7WDN+Qp+rk9OVL1/nAKfoXAsk0A4uAGuVbsqHrnCmNhw8CvdF1FsDyW/FIk8IFJurmk2IRr6/TOFI/i/fF6acHkq5BIvOxceXHWRpoXMy8xicGPUXh+d9TOmxeRYSyI7iJRvaeCPE5TsNnpVz8H0fYJ0wenfglFQkj2387MsvQOyQyq/CzRGYVtGMi81yIOKA59VZolpS7Ulzx0Olno9BhxTqqLGOSJowGSHTu/mDoxIqtTjcNtrymDGObeS0pzLSDNVMSipFd2R5WBNFdEkkWkMSCYuhvDVkVpA+ya6hGhx3uDNG6wGX+NYALRWnALVG6GCpvaD0wfUXPoIM2q/msWfRGwVdWasGXvOmpuSuMxR1r2zSNjFd0MlXH4/W0PLMbkiQYsK0WqDxx/KL/uXjh79/jRAUOLxCWVqfmtqaErkPWoN0iaeT0mqYid7IlUSnhIoyMZ3t5YkWz7ZCmuSoXq16r3yWE0Q5OzH6trcdrFC3C8pdLCZqxTbC8ByWMpJbyexGzLOJ9JXwIuumf2jiaUxPTzNP415XkGVrSvFZX+SiDFBH0Dw1itkWjDGIH+zoGKduUNoLyaDyOpudoo2lO98dUNBE2bMXNeIydzqCNsHNxfLfrplLT96rysNO/qoc2J7JFtqoBloGiW0tMdYxyvRyRzf+UNmqqezFUFqcDGVI49mRIr3Km9Yxipz+pfacuelpxm5WFZvfQb1Se4onrIO8bGqqq42+FhGiiHkz8P9gFo+itzYMbwukKhHyIfwe1wMDCePjeoJ6DhAjZt7g8oEr0ncPfnjOVPvTzDUmDR5Kag8Qg4m98mv4qqutMwQfqbfeQOwbxoTPsc+G2jKjH8KNDw7A/lZtve7LsbueribQ88IDY3AvFIZOztSxqw9TOmfnEqMR3/BIYSHDOg2L8uyAiIKEpsypWQ7SLsVWjP2LSVgtpWEGqgpswrGdCpljRjF7nPqU8oAlhbXnNkjwmIylpanT6zSUkwFWq0WUbQ2ug+ajxamrdJXzvJmLQWWwtS8tghrFshvoPOctoAx7TWQYaw2d3Fvvaytwp7F5Z9W6siq5w7obLGE1b5D77Dse2zOrdZdnQWldLVrQ9HDdXfejtnO/YpNVrsKGFWs98Y6RyfRjftUlri9qdvsbv0EaIWG3qBkW0T0xGAtIXQMcQcY81oTkhYQS2Pp5i+Au6blCoT6kcgk7s1W/e81Vc5QCNo+qJ1lbcgCQhBuZ5KumKBBKvAxAi/6LwkbAsb22XEL7nd5lMMokiQ7Rk27YyVCoZop/vQrs8z+6S/MPBc4iAbFIUAe74TxllYc33taUn6kGhclQ5DChbSjUUrLc1ptuYj0RUqq9OrQ8QYTMsQdxxn2ygn7fdOuxqbHZJyTolUVuDxUnJiU+QcosEEmhDNPTwL7prGD29/Rvq5WPkLiAAAA=="; }
        }
    }
}
